### ISSUE TITLE
What is the state of this app ?

### ISSUE THREAD

**Issue by gnouts** [YunoHost-Apps/glitch-soc_ynh#1]
Hi,

I am interested by glitch-soc app, but there is a WIP in the readme. What should I expect from this package ?

Tell me if I'm wrong, but if glitch-soc is a fork of mastodon relatively stable and the package mastodon_ynh is a stable and well integrated (LDAP and all) package, then glithc-soc_ynh should be stable enough for production.

What's missing in this package to be ranked at level7 on the yunohost scale ?

**Comment by lapineige** [comment]
:up:  I'm interested too :)

What's the status of this package, and its relationship with https://github.com/YunoHost-Apps/mastodon_ynh ?
As both apps are very similar, could that package benefit from the work on Mastodon package ? Then I guess only a few glitch-soc specific updates would be needed (update to latest commit for instance).

**Comment by yalh76** [comment]
Idk but don't plan to work on it ^^

**Comment by lapineige** [comment]
That's fine :)
:thinking:  I believe that working on a glitch-soc package could be done by reusing your work on Mastodon package, and "just" updating the source code and package version… which would create  zero extra work for you and little work for this package.

@Tagadda what do you think about that ?

**Comment by Tagadda** [comment]
@lapineige Yep, that's what I've done last year but I couldn't make it work at this time and I decided to wait for YunoHost 4.
I think forking again https://github.com/YunoHost-Apps/mastodon_ynh again is a good idea too, lots happens since last commit.

https://github.com/YunoHost-Apps/mastodon_ynh/pull/264 seems to be a cool branch to fork, let's wait until test is done :eyes:

**Comment by lapineige** [comment]
I can give you some help if needed :) (with limited knowledge and no server to test it 😅)

**Comment by Tagadda** [comment]
@lapineige I did some text search and replace yesterday, you can look at it on this branch https://github.com/YunoHost-Apps/glitch-soc_ynh/tree/rebase and this commit https://github.com/YunoHost-Apps/glitch-soc_ynh/commit/5fe7264febecb1911847640450db6245a443df62

The thing install but I've got an issue with assets not loading, but this could come from my testing environment so... I don't know yet ^^

**Comment by lapineige** [comment]
I did test an install on a server that a friend kindly lent for the test: same issue.

**Comment by Tagadda** [comment]
I'll wait until the upstream PR is merged, rebase and test again.

**Comment by Tagadda** [comment]
Upstream seems to be good now!
I did rebased again and the port is here https://github.com/YunoHost-Apps/glitch-soc_ynh/commit/43184e1904eb38dba11fa99be828bdfa736e6300

Installs and run great!

Only one issue remain : when you log in, you get an HTTP 422 Error and the page says "Vérification de sécurité échouée. Bloquez-vous les cookies ?", but you're logged in successfully anyway, you just have to go to `/web/timelines/home` ignoring the error page
I really have no clue

**Comment by lapineige** [comment]
I'll give it a look, but I'm unsure that I will have any clue about that…

**Comment by lapineige** [comment]
Since #2 is merged (in testing but still) I believe we can close this issue ?

**Comment by Tagadda** [comment]
The app installs now so I guess. I merged to master since the app was totally broken before.
